name: Checkout And Setup

on:
  workflow_call:

jobs:
  checkout-and-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 16
          registry-url: https://npm.pkg.github.com
          scope: "@dhruv-techapps"
          cache: "npm"
