name: Build Extension

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment of release'
        type: environment
        default: Development
        required: true
    
jobs:
  EnvSetup:
    name: Setup
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    outputs:
      NX_NAME: ${{ steps.set-output-defaults.outputs.NX_NAME}}
    steps:
      - name: set outputs with default values
        id: set-output-defaults
        run: |
          echo "NX_NAME=${{ vars.NAME }}" >> $GITHUB_OUTPUT
        
          
  build:
    needs: [EnvSetup]
    runs-on: ubuntu-latest
    steps:
    - name: Name
      id: name
      run: |
        echo "${{ needs.EnvSetup.outputs.NX_NAME == 'DEV' }}"
        echo "${{needs.EnvSetup.outputs.NX_NAME}}"
