name: Build Extension

on:
  workflow_dispatch:
  
env:
    NAME: Auto Clicker - AutoFill [DEV]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Name
      id: name
      run: |
        echo "NAME=${NAME,,}" >>${NAME}
        echo "NAME=${NAME//[^[:alnum:]]/_}" >>${NAME}

    - name: TEST
      run: |
        echo "${steps.name.NAME}"
