name: Build Extension

on:
  workflow_dispatch:
  
env:
    NAME: Auto Clicker - AutoFill [DEV]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Name
      id: name
      run: |
        echo "NAME=${NAME,,}" >>${GITHUB_ENV}
        echo "NAME=${NAME//[^[:alnum:]]/_}" >>${GITHUB_ENV}
        echo "${NAME}"

    - name: TEST
      run: |
        echo "${NAME}"
